service: bikelanes-api

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: v1

functions:
  report:
    handler: report.process
    events:
      - http:
          method: post
          path: report
          cors:
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
plugins:
  - serverless-offline

custom:
  serverless-offline:
    prefix: v1
    port: 4000