service: bikelanes-api

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: v1

functions:
  report:
    handler: report.process
    events:
      - http: post report

plugins:
  - serverless-offline

custom:
  serverless-offline:
    prefix: v1
    port: 4000